[package]
name = "comfy"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A comfy 2d game engine in Rust."
authors = ["Jakub Arnold <darthdeus@gmail.com>"]
homepage = "https://comfyengine.org/"
repository = "https://github.com/darthdeus/comfy"


[features]
default = ["color-backtrace", "quick-exit", "use-wgpu"]

dev = ["comfy-core/dev"]
blobs = []

memory-stats = ["comfy-core/memory-stats"]
color-backtrace = []
exit-after-startup = []

git-version = ["comfy-core/git-version"]

demo = []
embedded-assets = []
quick-exit = []
ci-release = ["comfy-core/ci-release", "comfy-wgpu/ci-release", "wayland"]

tracy = ["comfy-core/tracy", "comfy-wgpu/tracy"]

jemalloc = ["comfy-core/jemalloc"]
wayland = ["comfy-core/wayland"]

use-wgpu = ["comfy-wgpu"]

[dependencies]
comfy-wgpu = { path = "../comfy-wgpu", version = "0.2.0", optional = true }
comfy-core = { path = "../comfy-core", version = "0.2.0" }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
tracing-tracy = { version = "0.10.4", features = ["enable"] }
clap = { version = "4.4.10", features = ["derive"] }

[[example]]
name = "physics"
required-features = ["blobs"]
